application:
  jwt:
    secret: 2KOSMMJYO8
    expirationInMs: 604800000
  locales:
    ru: ru-RU
    en: en-US

spring:
  datasource:
    data: classpath:data.sql
    schema: classpath:schema.sql
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false

logging:
  level:
    ROOT: INFO

management:
  endpoints:
    web:
      exposure:
        exclude:
        include: health,metrics,loggers