application:
  locales:
    ru: ru-RU
    en: en-US
shell:
  out:
    info: CYAN
    success: GREEN
    warning: YELLOW
    error: RED
spring:
  shell:
    interactive:
      enabled: true
  datasource:
    data: classpath:data.sql
    schema: classpath:schema.sql