application:
  locales:
    ru: ru-RU
    en: en-US
shell:
  out:
    info: CYAN
    success: GREEN
    warning: YELLOW
    error: RED
spring:
  shell:
    interactive:
      enabled: true

  datasource:
    data: classpath:data.sql
    schema: classpath:schema.sql
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false

logging:
  level:
    ROOT: ERROR